name: Deploy Next.js with Docs

on:
  push:
    branches: [main]
    paths: ["docs/adr/**"] # Only trigger on ADR changes
  workflow_dispatch: # Enables manual triggering

permissions:
  contents: read
  pages: write
  id-token: write # ← This is what's missing

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the external Next.js repo as main
      - name: Checkout Next.js project
        uses: actions/checkout@v4
        with:
          repository: lugen4ro/adr-explorer
          path: ./

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build Next.js application
        env:
          GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }} # ← This extracts the repo name
        run: pnpm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./out" # or './dist' depending on Next.js config

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
